package de.readeckapp.ui.theme.sepia
import androidx.compose.ui.graphics.Color

// Colors created using https://material-foundation.github.io/material-theme-builder/

val primaryLight = Color(0xFF552C00)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF704214)
val onPrimaryContainerLight = Color(0xFFF1B179)
val secondaryLight = Color(0xFF552C00)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF704214)
val onSecondaryContainerLight = Color(0xFFF1B179)
val tertiaryLight = Color(0xFF552C00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF704214)
val onTertiaryContainerLight = Color(0xFFF1B179)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF4ECD8)
val onBackgroundLight = Color(0xFF201B17)
val surfaceLight = Color(0xFFF5E8C8)
val onSurfaceLight = Color(0xFF1C1B1A)
val surfaceVariantLight = Color(0xFFF3DFD1)
val onSurfaceVariantLight = Color(0xFF51443A)
val outlineLight = Color(0xFF847469)
val outlineVariantLight = Color(0xFFD6C3B6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF31302F)
val inverseOnSurfaceLight = Color(0xFFF4F0ED)
val inversePrimaryLight = Color(0xFFFBB980)
val surfaceDimLight = Color(0xFFDDD9D7)
val surfaceBrightLight = Color(0xFFFDF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F3F0)
val surfaceContainerLight = Color(0xFFF1EDEA)
val surfaceContainerHighLight = Color(0xFFECE7E5)
val surfaceContainerHighestLight = Color(0xFFE6E2DF)
