name: Build dev Release

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Run Unit-Tests with Gradle
        run: ./gradlew assembleRelease
      - name: Sign APK  
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "35.0.0"
      - name: Rename APK
        id: rename_artifact
        run: |
          TIMESTAMP=$(date +%Y%m%dT%H%M%S)
          COMMIT_SHA=$(git rev-parse --short HEAD)
          ARTIFACT_NAME="readeck-app"
          FILENAME="${ARTIFACT_NAME}-${TIMESTAMP}-${COMMIT_SHA}.apk"
          mv app/build/outputs/apk/release/app-release-unsigned-signed.apk "$FILENAME"
          sha256sum $FILENAME > checksums.txt
          echo "ARTIFACT_FILENAME=$FILENAME" >> "$GITHUB_OUTPUT"
      - name: Create release
        uses: ncipollo/release-action@v1.16.0
        with:
          allowUpdates: true
          draft: true
          prerelease: true
          name: ReadeckApp Snapshot Build
          body: |
            ## Release Notes - Snapshot Build from Develop Branch

            ReadeckApp Snapshot Build

            This release represents a snapshot build from the `develop` branch. It is **not intended for production use** and may contain unstable features, bugs, or incomplete functionality. This build is released to allow for early testing of the latest changes.

            This build includes all commits merged into the `develop` branch up to ${{ github.sha }}.

            **Thanks for testing!**
          commit: ${{ github.sha }}
          removeArtifacts: true
          artifacts: "${{ steps.rename_artifact.outputs.ARTIFACT_FILENAME }},checksums.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: dev-release
          path: |
            ${{ steps.rename_artifact.outputs.ARTIFACT_FILENAME }}
            checksums.txt
