name: Build Snapshot Release

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ${{ github.workspace }}/keystore.jks
      - name: Set Env Vars
        id: set_env
        run: |
          echo "TIMESTAMP=$(date +%Y%m%dT%H%M%S)" >> "$GITHUB_OUTPUT"
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: Build apk with Gradle
        run: ./gradlew assembleGithubSnapshotRelease
        env: 
          SNAPSHOT_VERSION_NAME: ${{ steps.set_env.outputs.TIMESTAMP }}-${{ steps.set_env.outputs.COMMIT_SHA }}
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE: ${{ github.workspace }}/keystore.jks
      - name: Rename APK
        id: rename_artifact
        run: |
          ARTIFACT_NAME="readeck-app"
          FILENAME="${ARTIFACT_NAME}-${{ steps.set_env.outputs.TIMESTAMP }}-${{ steps.set_env.outputs.COMMIT_SHA }}.apk"
          mv app/build/outputs/apk/githubSnapshot/release/app-githubSnapshot-release.apk "$FILENAME"
          sha256sum $FILENAME > checksums.txt
          echo "ARTIFACT_FILENAME=$FILENAME" >> "$GITHUB_OUTPUT"
      - name: Create or update develop-snapshot
        uses: joutvhu/create-tag@v1
        with:
          tag_name: develop-snapshot
          tag_sha: ${{ github.sha }}
          message: develop-snapshot
          on_tag_exists: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: ncipollo/release-action@v1.16.0
        with:
          allowUpdates: true
          prerelease: true
          name: ReadeckApp Snapshot Build
          body: |
            This release represents a snapshot build from the `develop` branch. It is **not intended for production use** and may contain unstable features, bugs, or incomplete functionality. This build is released to allow for early testing of the latest changes.

            This build includes all commits merged into the `develop` branch up to ${{ github.sha }}.

            **Thanks for testing!**
          commit: ${{ github.sha }}
          tag: develop-snapshot
          removeArtifacts: true
          omitDraftDuringUpdate: true
          artifacts: "${{ steps.rename_artifact.outputs.ARTIFACT_FILENAME }},checksums.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: dev-release
          path: |
            ${{ steps.rename_artifact.outputs.ARTIFACT_FILENAME }}
            checksums.txt
