name: Release Build and Github Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ${{ github.workspace }}/keystore.jks

      - name: Build and Sign Release APK
        run: ./gradlew assembleGithubReleaseRelease
        env: 
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE: ${{ github.workspace }}/keystore.jks

      - name: Get Version from Tag
        id: get_version
        run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Upload APK to GitHub Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release-${{ steps.get_version.outputs.version }}
          path: app/build/outputs/apk/githubRelease/release/*.apk

  create-release:
    needs: build-and-sign
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Version from Tag
        id: get_version
        run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Download Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-${{ steps.get_version.outputs.version }}
          path: ./artifacts # Download to a dedicated directory

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.16.0
        with:
          allowUpdates: false
          prerelease: true
          draft: true
          name: Release v${{ steps.get_version.outputs.version }}
          tag: ${{ github.ref }}
          artifacts: "./artifacts/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
